/*
This file is part of drain project software
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/

-- ----------------------------
-- SRID
-- ----------------------------
INSERT INTO gpkg_spatial_ref_sys (srs_name, srs_id, organization, organization_coordsys_id, definition) VALUES('USER SRID', <SRID_VALUE>, 'EPSG', <SRID_VALUE>, 'user_srid');




-- ---------------------------
-- INSERTS INTO SYS GPKG TABLES
-- ---------------------------

INSERT INTO tables_geom (table_name, isgeom) values
('ground', 'MULTIPOLYGON'),
('ground_roughness', 'MULTIPOLYGON'),
('ground_losses', 'MULTIPOLYGON'),
('roof', 'MULTIPOLYGON'),
('mesh_tin', 'MULTIPOLYGON'),
('mesh_roof', 'MULTIPOLYGON'),
('mesh_anchor_points', 'POINT'),
('mesh_anchor_lines', 'LINESTRING'),
('boundary_conditions', 'MULTILINESTRING'),
('link', 'LINESTRING'),
('gully', 'POINT'),
('inp_conduit', 'LINESTRING'),
('inp_subcatchment', 'MULTIPOLYGON'),
('inp_outlet', 'LINESTRING'),
('inp_orifice', 'LINESTRING'),
('inp_weir', 'LINESTRING'),
('inp_pump', 'LINESTRING'),
('inp_outfall', 'POINT'),
('inp_divider', 'POINT'),
('inp_storage', 'POINT'),
('inp_junction', 'POINT'),
('inp_raingage', 'POINT'),
('inp_dwf', 'POINT'),
('v_node', 'POINT'),
('v_arc', 'LINESTRING'),
('vi_conduits', 'LINESTRING'),
('vi_subcatchments', 'MULTIPOLYGON'),
('vi_outlets', 'LINESTRING'),
('vi_orifices', 'LINESTRING'),
('vi_weirs', 'LINESTRING'),
('vi_pumps', 'LINESTRING'),
('vi_outfalls', 'POINT'),
('vi_dividers', 'POINT'),
('vi_storage', 'POINT'),
('vi_junctions', 'POINT'),
('vi_raingages', 'POINT');



insert into tables_nogeom (table_name) values
('config_param_user'),
('config_csv'),
('config_typevalue'),
('cat_bscenario'),
('cat_file'),
('cat_arc'),
('cat_transects'),
('cat_curve'),
('cat_curve_value'),
('cat_timeseries'),
('cat_timeseries_value'),
('cat_landuses'),
('cat_grate'),
('cat_pattern'),
('cat_pattern_value'),
('cat_controls'),
('inp_files'),
('inp_inflow'),
('rpt_arc'),
('rpt_arcflow_sum'),
('rpt_arcpolload_sum'),
('rpt_arcpollutant_sum'),
('rpt_cat_result'),
('rpt_condsurcharge_sum'),
('rpt_continuity_errors'),
('rpt_control_actions_taken'),
('rpt_critical_elements'),
('rpt_flowclass_sum'),
('rpt_flowrouting_cont'),
('rpt_groundwater_cont'),
('rpt_high_conterrors'),
('rpt_high_flowinest_ind'),
('rpt_instability_index'),
('rpt_lidperformance_sum'),
('rpt_node'),
('rpt_nodedepth_sum'),
('rpt_nodeflooding_sum'),
('rpt_nodeinflow_sum'),
('rpt_nodesurcharge_sum'),
('rpt_outfallflow_sum'),
('rpt_outfallload_sum'),
('rpt_pumping_sum'),
('rpt_qualrouting_cont'),
('rpt_rainfall_dep'),
('rpt_routing_timestep'),
('rpt_runoff_qual'),
('rpt_runoff_quant'),
('rpt_storagevol_sum'),
('rpt_subcatchment'),
('rpt_subcatchrunoff_sum'),
('rpt_subcatchwashoff_sum'),
('rpt_summary_arc'),
('rpt_summary_crossection'),
('rpt_summary_node'),
('rpt_summary_raingage'),
('rpt_summary_subcatchment'),
('rpt_timestep_critelem'),
('rpt_warning_summary'),
('selector_rpt_compare'),
('selector_rpt_compare_tstep'),
('selector_rpt_main'),
('selector_rpt_main_tstep'),
('vi_curves'),
('vi_timeseries'),
('vi_patterns'),
('vi_landuses'),
('vi_subareas'),
('vi_losses'),
('vi_xsections'),
('vi_dwf'),
('vi_infiltration'),
('vi_title'),
('vi_files'),
('vi_options'),
('vi_controls'),
('vi_inflows'),
('vi_transects'),
('vi_report');


-- --------------
-- CONFIG_TYPEVALUE
-- --------------
INSERT INTO config_typevalue (rowid, typevalue, id, idval, addparam) VALUES
(1, 'nullvalue', '0', 'UNDEFINED', NULL),
(2, 'options_order', '0', 'Order 0', NULL),
(3, 'options_order', '1', 'Order 1', NULL),
(4, 'options_order', '10', 'Order 10', NULL),
(5, 'options_order', '101', 'Order 101', NULL),
(6, 'options_simulation_new', '0', 'New simulation', NULL),
(7, 'options_simulation_new', '1', 'Continue simulation', NULL),
(8, 'losses_zonal_assign', '1', 'Lineal	Type of zonal losses', NULL),
(9, 'losses_zonal_assign', '2', 'SCS', NULL),
(10, 'losses_zonal_assign', '3', 'Horton', NULL),
(11, 'losses_zonal_assign', '4', 'Green ampt', NULL),
(12, 'losses_zonal_assign', '5', 'SCSC', NULL),
(13, 'rain_class', '0', 'No_rain', NULL),
(14, 'rain_class', '1', 'Hyetogram', NULL),
(15, 'rain_class', '2', 'Raster', NULL),
(16, 'rain_class', '3', 'Raster interpolation', NULL),
(17, 'rain_format', '0', 'Intensity', NULL),
(18, 'rain_format', '1', 'Volume', NULL),
(19, 'plg_swmm_options', '0', 'Only gullies', NULL),
(20, 'plg_swmm_options', '1', 'Complete network', NULL),
(21, 'inp_value_yesno', 'YES', 'YES', NULL),
(22, 'inp_value_yesno', 'NO', 'NO', NULL),
(23, 'inp_options_dwfscenario', '1', 'Default', ''),
(24, 'inp_options_dwfscenario', '0', 'UNDEFINED', NULL),
(25, 'inp_options_force_main_eq', 'H-W', 'H-W', NULL),
(26, 'inp_options_force_main_eq', 'D-W', 'D-W', NULL),
(27, 'inp_options_inertial_damping', 'FULL', 'FULL', ''),
(28, 'inp_options_inertial_damping', 'NONE', 'NONE', NULL),
(29, 'inp_options_normal_flow_limited', 'BOTH', 'BOTH', NULL),
(30, 'inp_options_normal_flow_limited', 'FLOWDE', 'FLOWDE', NULL),
(31, 'inp_options_normal_flow_limited', 'SLOPE', 'SLOPE', NULL),
(32, 'inp_options_hydro_scenario', '1', 'Infiltration default value', NULL),
(33, 'inp_options_hydro_scenario', '0', 'UNDEFINED', NULL),
(34, 'inp_options_flow_units', 'CFS', 'CFS', NULL),
(35, 'inp_options_flow_units', 'CMS', 'CMS', NULL),
(36, 'inp_options_flow_units', 'GPM', 'GPM', NULL),
(37, 'inp_options_flow_units', 'LPS', 'LPS', NULL),
(38, 'inp_options_flow_units', 'MGD', 'MGD', NULL),
(39, 'inp_options_flow_units', 'MLD', 'MLD', NULL),
(40, 'inp_options_flow_routing', 'DYNWAVE', 'DYNWAVE', NULL),
(41, 'inp_options_flow_routing', 'KINWAVE', 'KINWAVE', NULL),
(42, 'inp_options_flow_routing', 'STEADY', 'STEADY', NULL),
(43, 'inp_options_link_offsets', 'ELEVATION', 'ELEVATION', NULL),
(44, 'inp_options_link_offsets', 'DEPTH', 'DEPTH', NULL),
(45, 'inp_options_networkmode', '1D', '1D SWMM', NULL),
(46, 'inp_options_networkmode', '1D2D', '1D/2D SWMM_IBER', NULL),
(47, 'inp_timeseries_type', 'EVAPORATION', 'EVAPORATION', NULL),
(48, 'inp_timeseries_type', 'INFLOW HYDROGRAPH', 'INFLOW HYDROGRAPH', NULL),
(49, 'inp_timeseries_type', 'RAINFALL ', 'RAINFALL', NULL),
(50, 'inp_timeseries_type', 'TEMPERATURE', 'TEMPERATURE', NULL),
(51, 'inp_timeseries_type', 'ORIFICE', 'ORIFICE', NULL),
(52, 'inp_timeseries_type', 'BC ELEVATION', 'BC ELEVATION', '{"header": ["", "Time\n(H:M)", "Elevation (m)"]}'),
(53, 'inp_timeseries_type', 'BC FLOW', 'BC FLOW', '{"header": ["", "Time\n(H:M)", "Q (m3/s)"]}'),
(54, 'inp_timeseries_timestype', 'ABSOLUTE', 'ABSOLUTE', NULL),
(55, 'inp_timeseries_timestype', 'FILE', 'FILE', NULL),
(56, 'inp_timeseries_timestype', 'RELATIVE', 'RELATIVE', NULL),
(57, 'inp_curve_type', 'CONTROL', 'CONTROL', '{"header": ["Value", "Setting"]}'),
(58, 'inp_curve_type', 'DIVERSION', 'DIVERSION', '{"header": ["Inflow", "Outflow"]}'),
(59, 'inp_curve_type', 'PUMP1', 'PUMP1', '{"header": ["Volume", "Flow"]}'),
(60, 'inp_curve_type', 'PUMP2', 'PUMP2', '{"header": ["Depth", "Flow"]}'),
(61, 'inp_curve_type', 'PUMP3', 'PUMP3', '{"header": ["Head", "Flow"]}'),
(62, 'inp_curve_type', 'PUMP4', 'PUMP4', '{"header": ["Depth", "Flow"]}'),
(63, 'inp_curve_type', 'RATING', 'RATING', '{"header": ["Head", "Outflow"]}'),
(64, 'inp_curve_type', 'SHAPE', 'SHAPE', '{"header": ["Depth/\nFull Depth", "Width/\nFull Depth"]}'),
(65, 'inp_curve_type', 'STORAGE', 'STORAGE', '{"header": ["Depth", "Area"]}'),
(66, 'inp_curve_type', 'TIDAL', 'TIDAL', '{"header": ["Hour", "Stage"]}'),
(67, 'inp_typevalue_pattern', 'DAILY', 'DAILY', NULL),
(68, 'inp_typevalue_pattern', 'HOURLY', 'HOURLY', NULL),
(69, 'inp_typevalue_pattern', 'WEEKEND', 'WEEKEND', NULL),
(70, 'inp_typevalue_pattern', 'MONTHLY', 'MONTHLY', NULL),
(71, 'inp_raster_type', 'INTENSITY', 'INTENSITY', NULL),
(72, 'inp_raster_type', 'DEPTH', 'DEPTH', NULL);