/*
This file is part of drain project software
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/

-- ---------------------------
-- INSERTS INTO SYS GPKG TABLES
-- ---------------------------

INSERT INTO tables_geom (table_name, isgeom) values
('sector', 'MULTIPOLYGON'),
('ground', 'MULTIPOLYGON'),
('ground_roughness', 'MULTIPOLYGON'),
('ground_losses', 'MULTIPOLYGON'),
('roof', 'MULTIPOLYGON'),
('mesh_tin', 'MULTIPOLYGON'),
('mesh_roof', 'MULTIPOLYGON'),
('mesh_anchor_points', 'POINT'),
('mesh_anchor_lines', 'LINESTRING'),
('link', 'LINESTRING'),
('gully', 'POINT'),
('inp_conduit', 'LINESTRING'),
('inp_subcatchment', 'MULTIPOLYGON'),
('inp_outlet', 'LINESTRING'),
('inp_orifice', 'LINESTRING'),
('inp_weir', 'LINESTRING'),
('inp_pump', 'LINESTRING'),
('inp_outfall', 'POINT'),
('inp_divider', 'POINT'),
('inp_storage', 'POINT'),
('inp_junction', 'POINT'),
('inp_raingage', 'POINT'),
('inp_dwf', 'POINT'),
('inp_inflow', 'POINT'),
('v_node', 'POINT'),
('v_arc', 'LINESTRING');



insert into tables_nogeom (table_name) values
('selector_sector'),
('selector_scenario'),
('config_param_user'),
('config_csv'),
('cat_scenario'),
('cat_arc'),
('cat_transects'),
('cat_curve'),
('cat_curve_value'),
('cat_timeseries'),
('cat_timeseries_value'),
('cat_landuses'),
('cat_grate'),
('cat_pattern'),
('cat_controls'),
('inp_files'),
('rpt_arc'),
('rpt_arcflow_sum'),
('rpt_arcpolload_sum'),
('rpt_arcpollutant_sum'),
('rpt_cat_result'),
('rpt_condsurcharge_sum'),
('rpt_continuity_errors'),
('rpt_control_actions_taken'),
('rpt_critical_elements'),
('rpt_flowclass_sum'),
('rpt_flowrouting_cont'),
('rpt_groundwater_cont'),
('rpt_high_conterrors'),
('rpt_high_flowinest_ind'),
('rpt_instability_index'),
('rpt_lidperformance_sum'),
('rpt_node'),
('rpt_nodedepth_sum'),
('rpt_nodeflooding_sum'),
('rpt_nodeinflow_sum'),
('rpt_nodesurcharge_sum'),
('rpt_outfallflow_sum'),
('rpt_outfallload_sum'),
('rpt_pumping_sum'),
('rpt_qualrouting_cont'),
('rpt_rainfall_dep'),
('rpt_routing_timestep'),
('rpt_runoff_qual'),
('rpt_runoff_quant'),
('rpt_storagevol_sum'),
('rpt_subcatchment'),
('rpt_subcatchrunoff_sum'),
('rpt_subcatchwashoff_sum'),
('rpt_summary_arc'),
('rpt_summary_crossection'),
('rpt_summary_node'),
('rpt_summary_raingage'),
('rpt_summary_subcatchment'),
('rpt_timestep_critelem'),
('rpt_warning_summary'),
('selector_rpt_compare'),
('selector_rpt_compare_tstep'),
('selector_rpt_main'),
('selector_rpt_main_tstep'),
('vi_curves'),
('vi_timeseries'),
('vi_patterns'),
('vi_landuses'),
('vi_subareas'),
('vi_losses'),
('vi_xsections'),
('vi_dwf'),
('vi_infiltration'),
('vi_raingages'),
('vi_conduits'),
('vi_subcatchments'),
('vi_outlets'),
('vi_orifices'),
('vi_weirs'),
('vi_pumps'),
('vi_outfalls'),
('vi_dividers'),
('vi_storage'),
('vi_junctions'),
('vi_title'),
('vi_files'),
('vi_options'),
('vi_controls'),
('vi_inflows'),
('vi_transects');