
/*
This file is part of drain project software
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/

-- ----------------------------------------
-- TRIGGERS FOR SYS GPKG TABLESPACE
-- ----------------------------------------

CREATE TRIGGER "trigger_delete_feature_count_sys_selector" AFTER DELETE ON "sys_selector" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('sys_selector'); END;
CREATE TRIGGER "trigger_delete_feature_count_selector_scenario" AFTER DELETE ON "selector_scenario" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('selector_scenario'); END;
CREATE TRIGGER "trigger_delete_feature_count_selector_sector" AFTER DELETE ON "selector_sector" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('selector_sector'); END;
CREATE TRIGGER "trigger_delete_feature_count_config_param_user" AFTER DELETE ON "config_param_user" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('config_param_user'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_scenario" AFTER DELETE ON "cat_scenario" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_scenario'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_curve" AFTER DELETE ON "cat_curve" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_curve'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_curve_value" AFTER DELETE ON "cat_curve_value" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_curve_value'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_timeseries" AFTER DELETE ON "cat_timeseries" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_timeseries'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_timeseries_value" AFTER DELETE ON "cat_timeseries_value" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_timeseries_value'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_landuses" AFTER DELETE ON "cat_landuses" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_landuses'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_grate" AFTER DELETE ON "cat_grate" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_grate'); END;
CREATE TRIGGER "trigger_delete_feature_count_cat_pattern" AFTER DELETE ON "cat_pattern" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('cat_pattern'); END;

CREATE TRIGGER "trigger_delete_feature_count_sector" AFTER DELETE ON "sector" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('sector'); END;
CREATE TRIGGER "trigger_delete_feature_count_polygon" AFTER DELETE ON "polygon"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('polygon'); END;
CREATE TRIGGER "trigger_delete_feature_count_manzone" AFTER DELETE ON "manzone"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('manzone'); END;
CREATE TRIGGER "trigger_delete_feature_count_losszone" AFTER DELETE ON "losszone"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('losszone'); END;
CREATE TRIGGER "trigger_delete_feature_count_roof" AFTER DELETE ON "roof" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('roof'); END;
CREATE TRIGGER "trigger_delete_feature_count_elem_tin" AFTER DELETE ON "elem_tin"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('elem_tin'); END;
CREATE TRIGGER "trigger_delete_feature_count_elem_edge" AFTER DELETE ON "elem_edge" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('elem_edge'); END;
CREATE TRIGGER "trigger_delete_feature_count_elem_vertex" AFTER DELETE ON "elem_vertex" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('elem_vertex'); END;
CREATE TRIGGER "trigger_delete_feature_count_raingage" AFTER DELETE ON "raingage" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('raingage'); END;
CREATE TRIGGER "trigger_delete_feature_count_conduit" AFTER DELETE ON "conduit" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('conduit'); END;
CREATE TRIGGER "trigger_delete_feature_count_subcatchment" AFTER DELETE ON "subcatchment" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('subcatchment'); END;
CREATE TRIGGER "trigger_delete_feature_count_outlet" AFTER DELETE ON "outlet" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('outlet'); END;
CREATE TRIGGER "trigger_delete_feature_count_orifice" AFTER DELETE ON "orifice" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('orifice'); END;
CREATE TRIGGER "trigger_delete_feature_count_weir" AFTER DELETE ON "weir" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('weir'); END;
CREATE TRIGGER "trigger_delete_feature_count_pump" AFTER DELETE ON "pump" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('pump'); END;
CREATE TRIGGER "trigger_delete_feature_count_outfall" AFTER DELETE ON "outfall" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('outfall'); END;
CREATE TRIGGER "trigger_delete_feature_count_divider" AFTER DELETE ON "divider" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('divider'); END;
CREATE TRIGGER "trigger_delete_feature_count_storage" AFTER DELETE ON "storage" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('storage'); END;
CREATE TRIGGER "trigger_delete_feature_count_junction" AFTER DELETE ON "junction" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('junction'); END;
CREATE TRIGGER "trigger_delete_feature_count_link" AFTER DELETE ON "link" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('link'); END;
CREATE TRIGGER "trigger_delete_feature_count_gully" AFTER DELETE ON "gully" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('gully'); END;

CREATE TRIGGER "trigger_insert_feature_count_sys_selector" AFTER INSERT ON "sys_selector" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('sys_selector'); END;
CREATE TRIGGER "trigger_insert_feature_count_selector_sector" AFTER INSERT ON "selector_sector" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('selector_sector'); END;
CREATE TRIGGER "trigger_insert_feature_count_selector_scenarior" AFTER INSERT ON "selector_scenario" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('selector_scenario'); END;
CREATE TRIGGER "trigger_insert_feature_count_config_param_user" AFTER INSERT ON "config_param_user" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('config_param_user'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_scenario" AFTER INSERT ON "cat_scenario" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_scenario'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_curve" AFTER INSERT ON "cat_curve" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_curve'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_curve_value" AFTER INSERT ON "cat_curve_value" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_curve_value'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_timeseries" AFTER INSERT ON "cat_timeseries" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_timeseries'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_timeseries_value" AFTER INSERT ON "cat_timeseries_value" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_timeseries_value'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_landuses" AFTER INSERT ON "cat_landuses" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_landuses'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_grate" AFTER INSERT ON "cat_grate" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_grate'); END;
CREATE TRIGGER "trigger_insert_feature_count_cat_pattern" AFTER INSERT ON "cat_pattern" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('cat_pattern'); END;

CREATE TRIGGER "trigger_insert_feature_count_sector" AFTER INSERT ON "sector" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('sector'); END;
CREATE TRIGGER "trigger_insert_feature_count_polygon" AFTER INSERT ON "polygon"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('polygon'); END;
CREATE TRIGGER "trigger_insert_feature_count_manzone" AFTER INSERT ON "manzone"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('manzone'); END;
CREATE TRIGGER "trigger_insert_feature_count_losszone" AFTER INSERT ON "losszone" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('losszone'); END;
CREATE TRIGGER "trigger_insert_feature_count_roof" AFTER INSERT ON "roof" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('roof'); END;
CREATE TRIGGER "trigger_insert_feature_count_elem_tin" AFTER INSERT ON "elem_tin"	BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('elem_tin'); END;
CREATE TRIGGER "trigger_insert_feature_count_elem_edge" AFTER INSERT ON "elem_edge" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('elem_edge'); END;
CREATE TRIGGER "trigger_insert_feature_count_elem_vertex" AFTER INSERT ON "elem_vertex" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('elem_vertex'); END;
CREATE TRIGGER "trigger_insert_feature_count_raingage" AFTER INSERT ON "raingage" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('raingage'); END;
CREATE TRIGGER "trigger_insert_feature_count_conduit" AFTER INSERT ON "conduit" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('conduit'); END;
CREATE TRIGGER "trigger_insert_feature_count_subcatchment" AFTER INSERT ON "subcatchment" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('subcatchment'); END;
CREATE TRIGGER "trigger_insert_feature_count_outlet" AFTER INSERT ON "outlet" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('outlet'); END;
CREATE TRIGGER "trigger_insert_feature_count_orifice" AFTER INSERT ON "orifice" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('orifice'); END;
CREATE TRIGGER "trigger_insert_feature_count_weir" AFTER INSERT ON "weir" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('weir'); END;
CREATE TRIGGER "trigger_insert_feature_count_pump" AFTER INSERT ON "pump" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('pump'); END;
CREATE TRIGGER "trigger_insert_feature_count_outfall" AFTER INSERT ON "outfall" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('outfall'); END;
CREATE TRIGGER "trigger_insert_feature_count_divider" AFTER INSERT ON "divider" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('divider'); END;
CREATE TRIGGER "trigger_insert_feature_count_storage" AFTER INSERT ON "storage" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('storage'); END;
CREATE TRIGGER "trigger_insert_feature_count_junction" AFTER INSERT ON "junction" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('junction'); END;
CREATE TRIGGER "trigger_insert_feature_count_link" AFTER INSERT ON "link" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('link'); END;
CREATE TRIGGER "trigger_insert_feature_count_gully" AFTER INSERT ON "gully" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('gully'); END;


CREATE TRIGGER "rtree_sector_geom_delete" AFTER DELETE ON "sector" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_sector_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_polygon_geom_delete" AFTER DELETE ON "polygon" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_polygon_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_manzone_geom_delete" AFTER DELETE ON "manzone" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_manzone_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_losszone_geom_delete" AFTER DELETE ON "losszone" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_losszone_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_roof_geom_delete" AFTER DELETE ON "roof" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_roof_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_elem_tin_geom_delete" AFTER DELETE ON "elem_tin" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_elem_tin_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_elem_edge_geom_delete" AFTER DELETE ON "elem_edge" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_elem_edge_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_elem_vertex_geom_delete" AFTER DELETE ON "elem_vertex" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_elem_vertex_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_raingage_geom_delete" AFTER DELETE ON "raingage" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_raingage_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_conduit_geom_delete" AFTER DELETE ON "conduit" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_conduit_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_subcatchment_geom_delete" AFTER DELETE ON "subcatchment" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_subcatchment_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_outlet_geom_delete" AFTER DELETE ON "outlet" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_outlet_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_orifice_geom_delete" AFTER DELETE ON "orifice" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_orifice_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_weir_geom_delete" AFTER DELETE ON "weir" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_weir_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_pump_geom_delete" AFTER DELETE ON "pump" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_pump_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_outfall_geom_delete" AFTER DELETE ON "outfall" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_outfall_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_divider_geom_delete" AFTER DELETE ON "divider" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_divider_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_storage_geom_delete" AFTER DELETE ON "storage" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_storage_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_junction_geom_delete" AFTER DELETE ON "junction" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_junction_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_link_geom_delete" AFTER DELETE ON "link" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_link_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_gully_geom_delete" AFTER DELETE ON "gully" WHEN (old."geom" NOT NULL) BEGIN DELETE FROM "rtree_gully_geom" WHERE id = OLD."fid"; END;

CREATE TRIGGER "rtree_sector_geom_insert" AFTER INSERT ON "sector" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_sector_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_polygon_geom_insert" AFTER INSERT ON "polygon" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_polygon_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_manzone_geom_insert" AFTER INSERT ON "manzone" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_manzone_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_losszone_geom_insert" AFTER INSERT ON "losszone" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_losszone_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_roof_geom_insert" AFTER INSERT ON "roof" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_roof_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_elem_tin_geom_insert" AFTER INSERT ON "elem_tin" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_elem_tin_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_elem_edge_geom_insert" AFTER INSERT ON "elem_edge" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_elem_edge_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_elem_vertex_geom_insert" AFTER INSERT ON "elem_vertex" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_elem_vertex_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_raingage_geom_insert" AFTER INSERT ON "raingage" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_raingage_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_conduit_geom_insert" AFTER INSERT ON "conduit" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_conduit_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_subcatchment_geom_insert" AFTER INSERT ON "subcatchment" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_subcatchment_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_outlet_geom_insert" AFTER INSERT ON "outlet" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_outlet_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_orifice_geom_insert" AFTER INSERT ON "orifice" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_orifice_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_weir_geom_insert" AFTER INSERT ON "weir" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_weir_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_pump_geom_insert" AFTER INSERT ON "pump" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_pump_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_outfall_geom_insert" AFTER INSERT ON "outfall" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_outfall_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_divider_geom_insert" AFTER INSERT ON "divider" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_divider_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_storage_geom_insert" AFTER INSERT ON "storage" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_storage_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_junction_geom_insert" AFTER INSERT ON "junction" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_junction_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_link_geom_insert" AFTER INSERT ON "link" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_link_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;
CREATE TRIGGER "rtree_gully_geom_insert" AFTER INSERT ON "gully" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_gully_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom") ); END;

CREATE TRIGGER "rtree_sector_geom_update1" AFTER UPDATE OF "geom" ON "sector" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_sector_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_polygon_geom_update1" AFTER UPDATE OF "geom" ON "polygon" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_polygon_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_manzone_geom_update1" AFTER UPDATE OF "geom" ON "manzone" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_manzone_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_losszone_geom_update1" AFTER UPDATE OF "geom" ON "losszone" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_losszone_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_roof_geom_update1" AFTER UPDATE OF "geom" ON "roof" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_roof_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_elem_tin_geom_update1" AFTER UPDATE OF "geom" ON "elem_tin" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_elem_tin_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_elem_edge_geom_update1" AFTER UPDATE OF "geom" ON "elem_edge" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_elem_edge_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_elem_vertex_geom_update1" AFTER UPDATE OF "geom" ON "elem_vertex" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_elem_vertex_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_raingage_geom_update1" AFTER UPDATE OF "geom" ON "raingage" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_raingage_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_conduit_geom_update1" AFTER UPDATE OF "geom" ON "conduit" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_conduit_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_subcatchment_geom_update1" AFTER UPDATE OF "geom" ON "subcatchment" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_subcatchment_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_outlet_geom_update1" AFTER UPDATE OF "geom" ON "outlet" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_outlet_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_orifice_geom_update1" AFTER UPDATE OF "geom" ON "orifice" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_orifice_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_weir_geom_update1" AFTER UPDATE OF "geom" ON "weir" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_weir_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_pump_geom_update1" AFTER UPDATE OF "geom" ON "pump" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_pump_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_outfall_geom_update1" AFTER UPDATE OF "geom" ON "outfall" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_outfall_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_divider_geom_update1" AFTER UPDATE OF "geom" ON "divider" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_divider_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_storage_geom_update1" AFTER UPDATE OF "geom" ON "storage" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_storage_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_junction_geom_update1" AFTER UPDATE OF "geom" ON "junction" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_junction_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_link_geom_update1" AFTER UPDATE OF "geom" ON "link" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_link_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_gully_geom_update1" AFTER UPDATE OF "geom" ON "gully" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN INSERT OR REPLACE INTO "rtree_gully_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;

CREATE TRIGGER "rtree_sector_geom_update2" AFTER UPDATE OF "geom" ON "sector" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_sector_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_polygon_geom_update2" AFTER UPDATE OF "geom" ON "polygon" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_polygon_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_manzone_geom_update2" AFTER UPDATE OF "geom" ON "manzone" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_manzone_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_losszone_geom_update2" AFTER UPDATE OF "geom" ON "losszone" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_losszone_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_roof_geom_update2" AFTER UPDATE OF "geom" ON "roof" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_roof_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_elem_tin_geom_update2" AFTER UPDATE OF "geom" ON "elem_tin" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_tin_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_elem_edge_geom_update2" AFTER UPDATE OF "geom" ON "elem_edge" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_edge_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_elem_vertex_geom_update2" AFTER UPDATE OF "geom" ON "elem_vertex" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_vertex_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_raingage_geom_update2" AFTER UPDATE OF "geom" ON "raingage" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_raingage_geom" WHERE id= OLD."fid"; END;
CREATE TRIGGER "rtree_conduit_geom_update2" AFTER UPDATE OF "geom" ON "conduit" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_conduit_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_subcatchment_geom_update2" AFTER UPDATE OF "geom" ON "subcatchment" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_subcatchment_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_outlet_geom_update2" AFTER UPDATE OF "geom" ON "outlet" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_outlet_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_orifice_geom_update2" AFTER UPDATE OF "geom" ON "orifice" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_orifice_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_weir_geom_update2" AFTER UPDATE OF "geom" ON "weir" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_weir_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_pump_geom_update2" AFTER UPDATE OF "geom" ON "pump" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_pump_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_outfall_geom_update2" AFTER UPDATE OF "geom" ON "outfall" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_outfall_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_divider_geom_update2" AFTER UPDATE OF "geom" ON "divider" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_divider_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_storage_geom_update2" AFTER UPDATE OF "geom" ON "storage" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_storage_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_junction_geom_update2" AFTER UPDATE OF "geom" ON "junction" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_junction_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_link_geom_update2" AFTER UPDATE OF "geom" ON "link" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_link_geom" WHERE id = OLD."fid"; END;
CREATE TRIGGER "rtree_gully_geom_update2" AFTER UPDATE OF "geom" ON "gully" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_gully_geom" WHERE id = OLD."fid"; END;

CREATE TRIGGER "rtree_sector_geom_update3" AFTER UPDATE ON "sector" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_sector_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_sector_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_polygon_geom_update3" AFTER UPDATE ON "polygon" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_polygon_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_polygon_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_manzone_geom_update3" AFTER UPDATE ON "manzone" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_manzone_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_manzone_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_losszone_geom_update3" AFTER UPDATE ON "losszone" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_losszone_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_losszone_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_roof_geom_update3" AFTER UPDATE ON "roof" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_roof_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_roof_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_elem_tin_geom_update3" AFTER UPDATE ON "elem_tin" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_tin_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_elem_tin_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_elem_edge_geom_update3" AFTER UPDATE ON "elem_edge" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_edge_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_elem_edge_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_elem_vertex_geom_update3" AFTER UPDATE ON "elem_vertex" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_vertex_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_elem_vertex_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_raingage_geom_update3" AFTER UPDATE ON "raingage" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_raingage_geom" WHERE id= OLD."fid"; INSERT OR REPLACE INTO "rtree_raingage_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_conduit_geom_update3" AFTER UPDATE ON "conduit" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_conduit_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_conduit_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_subcatchment_geom_update3" AFTER UPDATE ON"subcatchment" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_subcatchment_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_subcatchment_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_outlet_geom_update3" AFTER UPDATE ON "outlet" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_outlet_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_outlet_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_orifice_geom_update3" AFTER UPDATE ON "orifice" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_orifice_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_orifice_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_weir_geom_update3" AFTER UPDATE ON "weir" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_weir_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_weir_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_pump_geom_update3" AFTER UPDATE ON "pump" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_pump_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_pump_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_outfall_geom_update3" AFTER UPDATE ON "outfall" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_outfall_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_outfall_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_divider_geom_update3" AFTER UPDATE ON "divider" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_divider_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_divider_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_storage_geom_update3" AFTER UPDATE ON "storage" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_storage_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_storage_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_junction_geom_update3" AFTER UPDATE ON "junction" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_junction_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_junction_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_link_geom_update3" AFTER UPDATE ON "link" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_link_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_link_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;
CREATE TRIGGER "rtree_gully_geom_update3" AFTER UPDATE ON "gully" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_gully_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_gully_geom" VALUES (NEW."fid", ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"), ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;

CREATE TRIGGER "rtree_sector_geom_update4" AFTER UPDATE ON "sector" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_sector_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_polygon_geom_update4" AFTER UPDATE ON "polygon" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_polygon_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_manzone_geom_update4" AFTER UPDATE ON "manzone" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_manzone_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_losszone_geom_update4" AFTER UPDATE ON "losszone" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_losszone_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_roof_geom_update4" AFTER UPDATE ON "roof" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_roof_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_elem_tin_geom_update4" AFTER UPDATE ON "elem_tin" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_tin_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_elem_edge_geom_update4" AFTER UPDATE ON "elem_edge" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_edge_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_elem_vertex_geom_update4" AFTER UPDATE ON "elem_vertex" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_elem_vertex_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_raingage_geom_update4" AFTER UPDATE ON "raingage" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_raingage_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_conduit_geom_update4" AFTER UPDATE ON "conduit" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_conduit_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_subcatchment_geom_update4" AFTER UPDATE ON "subcatchment" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_subcatchment_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_outlet_geom_update4" AFTER UPDATE ON "outlet" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_outlet_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_orifice_geom_update4" AFTER UPDATE ON "orifice" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_orifice_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_weir_geom_update4" AFTER UPDATE ON "weir" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_weir_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_pump_geom_update4" AFTER UPDATE ON "pump" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_pump_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_outfall_geom_update4" AFTER UPDATE ON "outfall" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_outfall_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_divider_geom_update4" AFTER UPDATE ON "divider" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_divider_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_storage_geom_update4" AFTER UPDATE ON "storage" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_storage_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_junction_geom_update4" AFTER UPDATE ON "junction" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_junction_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_link_geom_update4" AFTER UPDATE ON "link" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_link_geom" WHERE id IN (OLD."fid", NEW."fid"); END;
CREATE TRIGGER "rtree_gully_geom_update4" AFTER UPDATE ON "gully" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom") ) BEGIN DELETE FROM "rtree_gully_geom" WHERE id IN (OLD."fid", NEW."fid"); END;